### ISSUE TITLE
gulp-util@3.0.8 is deprecated

### ISSUE THREAD

**Issue by chriz74x** [kevva/gulp-decompress#14]
Hello, your package is using a deprecated version. Please check guidelines:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by pieterbeulque** [comment]
This is already resolved in #13 and waiting for merge

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/gulp-decompress/commit/d3fdff17810f757056503b0f81a8c06f3fa9dc60.
