### ISSUE TITLE
gulp-util deprecated

### ISSUE THREAD

**Issue by bitwitch** [kevva/gulp-decompress#17]
The authors of gulp-util are deprecating gulp-util and request that package authors use the following API replacements:    

gutil.File => https://www.npmjs.com/package/vinyl
gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext  
gutil.colors => https://www.npmjs.com/package/ansi-colors  
gutil.date => https://www.npmjs.com/package/date-format  
gutil.log => https://www.npmjs.com/package/fancy-log  
gutil.template => https://www.npmjs.com/package/lodash.template  
gutil.env => https://www.npmjs.com/package/minimist   
gutil.beep => https://www.npmjs.com/package/beeper  
gutil.noop => https://www.npmjs.com/package/through2   
gutil.isStream => Use the .isStream() method on Vinyl objects   
gutil.isBuffer => Use the .isBuffer() method on Vinyl objects   
gutil.isNull => Use the .isNull() method on Vinyl objects   
gutil.linefeed => Use the string '\n' in your code   
gutil.combine => https://www.npmjs.com/package/multipipe   
gutil.buffer => https://www.npmjs.com/package/list-stream   
gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by demurgos** [comment]
This package already dropped its dependency on gulp-util.

- https://github.com/kevva/gulp-decompress/issues/12
- https://github.com/kevva/gulp-decompress/issues/14
- https://github.com/kevva/gulp-decompress/pull/13
- https://github.com/kevva/gulp-decompress/commit/d3fdff17810f757056503b0f81a8c06f3fa9dc60
