### ISSUE TITLE
Multiple zip files extracted to same path

### ISSUE THREAD

**Issue by Susovan87** [kevva/gulp-decompress#2]
I wonder if there is any option available to extract multiple zip files to it's own directory.

Let me explain what I mean. I have few bundles named `bundle1.zip`, `bundle2.zip` .. 
Now the below code extracted all files (irrespective of whether it is in `bundle1.zip` or `bundle2.zip`) at the `dist` folder.

```javascript
gulp.task('default', function () {
    return gulp.src('*.{tar,tar.bz2,tar.gz,zip}')
        .pipe(decompress())
        .pipe(gulp.dest('dist'));
});
```

My expectation here, `bundle1.zip` should get extracted to `dist/bundle1` directory, `bundle2.zip` should get extracted to `dist/bundle2` directory and so on..

Can I do that with current implementation?

If you accept it as an issue, I will be more than happy to contribute, to close the same :)

**Comment by shinnn** [comment]
The easiest way to fix this problem is to `zip` your files with the top-level directory.

```sh
$ mkdir bundle1
# add your files to the `bundle1` directory
$ zip bundle1.zip bundle1
```

**Comment by Susovan87** [comment]
I agree, it could be the easiest solution possible. Unfortunately in my case these bundles are not created by us and we do not have any control about it's creation.

Here my point is, if `gulp-decompress` can extract multiple zip files at a single shot, then it is quite expected that it takes care about source of extracted files.

**Comment by shinnn** [comment]
> Unfortunately in my case these bundles are not created by us and we do not have any control over it's creation.

So, you can use [gulp-rename](https://github.com/hparra/gulp-rename) like below instead.

```js
'use strict';
const path = require('path');
const gulp = require('gulp');
const decompress = require('decompress');
const rename = require('gulp-rename');

gulp.task('default', () => {
    return gulp.src('*.{tar,tar.bz2,tar.gz,zip}')
        .pipe(rename(pathObj => {
          pathObj.dirname = path.join(pathObj.dirname, pathObj.basename);
          return pathObj;
        }))
        .pipe(decompress())
        .pipe(gulp.dest('dist'));
});
```

**Comment by Susovan87** [comment]
Got the idea, thanks for helping :+1:

**Comment by Fanus** [comment]
This still doesn't put it in a folder which name is the same as the filename of the .zip file. Is there a method to get that?
@Susovan87 perhaps you can share what you finally did?

**Comment by MatthD** [comment]
I did it in a PR https://github.com/kevva/gulp-decompress/pull/11

**Comment by talevv** [comment]
You can do it with the `unzip` package and create the gulp task manually. Here is an example:

```javascript
function myGulpTask() {
  const destination = './public/test';
  const source = './test';
  
  return new Promise((resolve) => {    
    if (!fs.existsSync(destination)){      
      fs.mkdirSync(destination);
    }
    fs.readdirSync(source).forEach(file => {
      fs.createReadStream(`${source}/${file}`).pipe(unzip.Extract({ path: `${destination}/${file.replace('.zip', '')}` }));
    })
    resolve()
  });
}
```

it's going to put all zips into separeted directories
