### ISSUE TITLE
Decompress damage the OSX app in zip file

### ISSUE THREAD

**Issue by meowlab** [kevva/gulp-decompress#3]
You can download zip from https://github.com/atom/electron/releases/download/v0.35.2/electron-v0.35.2-darwin-x64.zip and have a try. The 'Electron.app' in zip file should be okay after decompress.

**Comment by Mossop** [comment]
The problem here is that symlinks aren't being extracted properly

**Comment by kevva** [comment]
This is fixed in `2.0.0`.
