### ISSUE TITLE
Option 'mode' not working

### ISSUE THREAD

**Issue by kapi** [kevva/gulp-decompress#6]
I'm using gulp-decompress for a zip file. The option 'mode' is ignored when calling decompress({mode: '777'}). After decompression none of the unzipped files has any permissions: 
----------  1 user group  327 Feb 17 10:35 file

**Comment by mrbinr** [comment]
Hi,
I have same problem, i've tried decompress({strip: 1, mode:'644'}) or decompress({strip: 1, mode:'0644'}) or decompress({strip: 1, mode:'777'}) and it doesn't work
---------- 1 user group .....

**Comment by kevva** [comment]
You can set `mode` on each file using the `map` option now https://github.com/kevva/decompress#map.
