### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by dewdad** [kevva/gulp-decompress#7]
gulp.src('./downloads/apache-maven-3.3.9-bin.zip')
    .pipe(decompress())
    .pipe(gulp.dest('./assets'))

produces:
assets
 apache-maven-3.3.9-bin (file instead of dir)

**Comment by shinnn** [comment]
Do you `return` a `gulp.src` stream inside the task function? [*`return` is required.*](https://github.com/gulpjs/gulp/blob/master/docs/API.md#return-a-stream)

**Comment by dewdad** [comment]
I did not return the pipeline from the task if that is what you mean.

**Comment by danielehrhardt** [comment]
Some Solution here?

Switched to:
```
gulp.task('prepareNodejsBinaries', cb => {
    gulp.src(path.join(__dirname, 'files/node-v18.15.0-linux-x64.tar.gz'))
        .pipe(gunzip())
        .pipe(untar())
        .pipe(gulp.dest(nestJsPath + '/build/nodejs'));
    cb();
});
const gunzip = require('gulp-gunzip');
const untar = require('gulp-untar');
```
