### ISSUE TITLE
Some ZIP files containing subdirectories cause 'Error: EEXIST'

### ISSUE THREAD

**Issue by dcwarwick** [kevva/gulp-decompress#9]
I have found some ZIP files which cause errors like the following when processed by ```gulp-decompress```:

![image](https://cloud.githubusercontent.com/assets/6385315/17983219/6be671d6-6b03-11e6-99b6-9af738e64232.png)

Here is an example ```gulpfile.js``` and a ```test.zip``` (which should be placed into a ```src``` directory). ```gulp unzip``` should unzip the file into ```dist```, but instead produces the above error.

```javascript
const gulp = require('gulp');
const decompress = require('gulp-decompress');

gulp.task('unzip', () =>
  gulp.src('src/test.zip')
    .pipe(decompress())
    .pipe(gulp.dest('dist'))
);
```
[test.zip](https://github.com/kevva/gulp-decompress/files/437925/test.zip)

The problem appears to be that for certain ZIP files the object in the files array produced by ```decompress``` corresponding to the subdirectories has something in the ```data``` field. That 'something' may be an empty string, but Vinyl ```File``` objects that are given *anything* other than ```null``` for their contents claim to be files, not directories, even if the ```stat``` identifies them as directories! See https://github.com/gulpjs/vinyl/blob/master/index.js line 60. ```gulp-decompress``` is then simply copying the ```data``` field as the ```contents``` for a new ```File``` object, and this causes the above error because the subdirectory is being created as a zero-byte file rather than a directory, and when a file that is supposed to be inside that directory comes along the error arises.

**Comment by dcwarwick** [comment]
ZIP files produced on OSX El Capitan, for example, exhibit this issue (that's where I created the ```test.zip``` above).

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/gulp-decompress/commit/f294b06d188adfde8dfa3fbb72b4fac67e00c8a3.
